### ISSUE TITLE
API call out of date

### ISSUE THREAD

**Issue by chapmanc** [AlexisDeschamps/portfolio-rebalancer#5]
Looks like the api for pricing has changed and your code is out of date
![screen shot 2018-12-06 at 12 56 13 pm](https://user-images.githubusercontent.com/6537530/49611475-80e82000-f956-11e8-9ef7-8b668a09998e.png)

**Comment by chapmanc** [comment]
Just try to load any of the balancers and the prices don't load.

**Comment by TiraelSedai** [comment]
@chapmanc this is the response for any errors in API. Can you post the full request?

This works fine:
`https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=TSLA&interval=5min&apikey=mysecretkey`
This yields same error as you see:
`https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=BULL&interval=5min&apikey=mysecretkey`

**Comment by chapmanc** [comment]
When I load the app it errors out these queries  the key 

https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=XAW&interval=1min&apikey=<key_from _app>&outputsize=compact

**Comment by chapmanc** [comment]
Just got sometime to look at this... it seems alphaadvantage now insists on suffix for the Exchange. so XAW.TO works for TSX
